/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostAccountUsageBillingRateAdjustmentRequest struct for PostAccountUsageBillingRateAdjustmentRequest
type PostAccountUsageBillingRateAdjustmentRequest struct {
	BillingCost float32 `json:"billingCost"`
}

// NewPostAccountUsageBillingRateAdjustmentRequest instantiates a new PostAccountUsageBillingRateAdjustmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostAccountUsageBillingRateAdjustmentRequest(billingCost float32) *PostAccountUsageBillingRateAdjustmentRequest {
	this := PostAccountUsageBillingRateAdjustmentRequest{}
	this.BillingCost = billingCost
	return &this
}

// NewPostAccountUsageBillingRateAdjustmentRequestWithDefaults instantiates a new PostAccountUsageBillingRateAdjustmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostAccountUsageBillingRateAdjustmentRequestWithDefaults() *PostAccountUsageBillingRateAdjustmentRequest {
	this := PostAccountUsageBillingRateAdjustmentRequest{}
	return &this
}

// GetBillingCost returns the BillingCost field value
func (o *PostAccountUsageBillingRateAdjustmentRequest) GetBillingCost() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BillingCost
}

// GetBillingCostOk returns a tuple with the BillingCost field value
// and a boolean to check if the value has been set.
func (o *PostAccountUsageBillingRateAdjustmentRequest) GetBillingCostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingCost, true
}

// SetBillingCost sets field value
func (o *PostAccountUsageBillingRateAdjustmentRequest) SetBillingCost(v float32) {
	o.BillingCost = v
}

func (o PostAccountUsageBillingRateAdjustmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["billingCost"] = o.BillingCost
	}
	return json.Marshal(toSerialize)
}

type NullablePostAccountUsageBillingRateAdjustmentRequest struct {
	value *PostAccountUsageBillingRateAdjustmentRequest
	isSet bool
}

func (v NullablePostAccountUsageBillingRateAdjustmentRequest) Get() *PostAccountUsageBillingRateAdjustmentRequest {
	return v.value
}

func (v *NullablePostAccountUsageBillingRateAdjustmentRequest) Set(val *PostAccountUsageBillingRateAdjustmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAccountUsageBillingRateAdjustmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAccountUsageBillingRateAdjustmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAccountUsageBillingRateAdjustmentRequest(val *PostAccountUsageBillingRateAdjustmentRequest) *NullablePostAccountUsageBillingRateAdjustmentRequest {
	return &NullablePostAccountUsageBillingRateAdjustmentRequest{value: val, isSet: true}
}

func (v NullablePostAccountUsageBillingRateAdjustmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAccountUsageBillingRateAdjustmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


