/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AccountStatsResponseDailyInner struct for AccountStatsResponseDailyInner
type AccountStatsResponseDailyInner struct {
	Date string `json:"date"`
	Amount float32 `json:"amount"`
}

// NewAccountStatsResponseDailyInner instantiates a new AccountStatsResponseDailyInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountStatsResponseDailyInner(date string, amount float32) *AccountStatsResponseDailyInner {
	this := AccountStatsResponseDailyInner{}
	this.Date = date
	this.Amount = amount
	return &this
}

// NewAccountStatsResponseDailyInnerWithDefaults instantiates a new AccountStatsResponseDailyInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountStatsResponseDailyInnerWithDefaults() *AccountStatsResponseDailyInner {
	this := AccountStatsResponseDailyInner{}
	return &this
}

// GetDate returns the Date field value
func (o *AccountStatsResponseDailyInner) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *AccountStatsResponseDailyInner) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *AccountStatsResponseDailyInner) SetDate(v string) {
	o.Date = v
}

// GetAmount returns the Amount field value
func (o *AccountStatsResponseDailyInner) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AccountStatsResponseDailyInner) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AccountStatsResponseDailyInner) SetAmount(v float32) {
	o.Amount = v
}

func (o AccountStatsResponseDailyInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["date"] = o.Date
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableAccountStatsResponseDailyInner struct {
	value *AccountStatsResponseDailyInner
	isSet bool
}

func (v NullableAccountStatsResponseDailyInner) Get() *AccountStatsResponseDailyInner {
	return v.value
}

func (v *NullableAccountStatsResponseDailyInner) Set(val *AccountStatsResponseDailyInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountStatsResponseDailyInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountStatsResponseDailyInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountStatsResponseDailyInner(val *AccountStatsResponseDailyInner) *NullableAccountStatsResponseDailyInner {
	return &NullableAccountStatsResponseDailyInner{value: val, isSet: true}
}

func (v NullableAccountStatsResponseDailyInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountStatsResponseDailyInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


