/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AccountResponse struct for AccountResponse
type AccountResponse struct {
	BusinessId string `json:"businessId"`
	AccountId string `json:"accountId"`
	AccountName *string `json:"accountName,omitempty"`
	CreatedAt float32 `json:"createdAt"`
	ModifiedAt float32 `json:"modifiedAt"`
	Balance float32 `json:"balance"`
	UsageBillingRate float32 `json:"usageBillingRate"`
	RemainingHoursOnBalance *float32 `json:"remainingHoursOnBalance,omitempty"`
}

// NewAccountResponse instantiates a new AccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountResponse(businessId string, accountId string, createdAt float32, modifiedAt float32, balance float32, usageBillingRate float32) *AccountResponse {
	this := AccountResponse{}
	this.BusinessId = businessId
	this.AccountId = accountId
	this.CreatedAt = createdAt
	this.ModifiedAt = modifiedAt
	this.Balance = balance
	this.UsageBillingRate = usageBillingRate
	return &this
}

// NewAccountResponseWithDefaults instantiates a new AccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountResponseWithDefaults() *AccountResponse {
	this := AccountResponse{}
	return &this
}

// GetBusinessId returns the BusinessId field value
func (o *AccountResponse) GetBusinessId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessId
}

// GetBusinessIdOk returns a tuple with the BusinessId field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetBusinessIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessId, true
}

// SetBusinessId sets field value
func (o *AccountResponse) SetBusinessId(v string) {
	o.BusinessId = v
}

// GetAccountId returns the AccountId field value
func (o *AccountResponse) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AccountResponse) SetAccountId(v string) {
	o.AccountId = v
}

// GetAccountName returns the AccountName field value if set, zero value otherwise.
func (o *AccountResponse) GetAccountName() string {
	if o == nil || o.AccountName == nil {
		var ret string
		return ret
	}
	return *o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetAccountNameOk() (*string, bool) {
	if o == nil || o.AccountName == nil {
		return nil, false
	}
	return o.AccountName, true
}

// HasAccountName returns a boolean if a field has been set.
func (o *AccountResponse) HasAccountName() bool {
	if o != nil && o.AccountName != nil {
		return true
	}

	return false
}

// SetAccountName gets a reference to the given string and assigns it to the AccountName field.
func (o *AccountResponse) SetAccountName(v string) {
	o.AccountName = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AccountResponse) GetCreatedAt() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetCreatedAtOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AccountResponse) SetCreatedAt(v float32) {
	o.CreatedAt = v
}

// GetModifiedAt returns the ModifiedAt field value
func (o *AccountResponse) GetModifiedAt() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetModifiedAtOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedAt, true
}

// SetModifiedAt sets field value
func (o *AccountResponse) SetModifiedAt(v float32) {
	o.ModifiedAt = v
}

// GetBalance returns the Balance field value
func (o *AccountResponse) GetBalance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetBalanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *AccountResponse) SetBalance(v float32) {
	o.Balance = v
}

// GetUsageBillingRate returns the UsageBillingRate field value
func (o *AccountResponse) GetUsageBillingRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.UsageBillingRate
}

// GetUsageBillingRateOk returns a tuple with the UsageBillingRate field value
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetUsageBillingRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsageBillingRate, true
}

// SetUsageBillingRate sets field value
func (o *AccountResponse) SetUsageBillingRate(v float32) {
	o.UsageBillingRate = v
}

// GetRemainingHoursOnBalance returns the RemainingHoursOnBalance field value if set, zero value otherwise.
func (o *AccountResponse) GetRemainingHoursOnBalance() float32 {
	if o == nil || o.RemainingHoursOnBalance == nil {
		var ret float32
		return ret
	}
	return *o.RemainingHoursOnBalance
}

// GetRemainingHoursOnBalanceOk returns a tuple with the RemainingHoursOnBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountResponse) GetRemainingHoursOnBalanceOk() (*float32, bool) {
	if o == nil || o.RemainingHoursOnBalance == nil {
		return nil, false
	}
	return o.RemainingHoursOnBalance, true
}

// HasRemainingHoursOnBalance returns a boolean if a field has been set.
func (o *AccountResponse) HasRemainingHoursOnBalance() bool {
	if o != nil && o.RemainingHoursOnBalance != nil {
		return true
	}

	return false
}

// SetRemainingHoursOnBalance gets a reference to the given float32 and assigns it to the RemainingHoursOnBalance field.
func (o *AccountResponse) SetRemainingHoursOnBalance(v float32) {
	o.RemainingHoursOnBalance = &v
}

func (o AccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["businessId"] = o.BusinessId
	}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if o.AccountName != nil {
		toSerialize["accountName"] = o.AccountName
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["modifiedAt"] = o.ModifiedAt
	}
	if true {
		toSerialize["balance"] = o.Balance
	}
	if true {
		toSerialize["usageBillingRate"] = o.UsageBillingRate
	}
	if o.RemainingHoursOnBalance != nil {
		toSerialize["remainingHoursOnBalance"] = o.RemainingHoursOnBalance
	}
	return json.Marshal(toSerialize)
}

type NullableAccountResponse struct {
	value *AccountResponse
	isSet bool
}

func (v NullableAccountResponse) Get() *AccountResponse {
	return v.value
}

func (v *NullableAccountResponse) Set(val *AccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountResponse(val *AccountResponse) *NullableAccountResponse {
	return &NullableAccountResponse{value: val, isSet: true}
}

func (v NullableAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


