# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.9
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class AllAccountsResponseAccounts(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'items': 'AccountResponse',
        'count': 'float',
        'scanned_count': 'float',
        'last_evaluated_key': 'dict(str, str)'
    }

    attribute_map = {
        'items': 'Items',
        'count': 'Count',
        'scanned_count': 'ScannedCount',
        'last_evaluated_key': 'LastEvaluatedKey'
    }

    def __init__(self, items=None, count=None, scanned_count=None, last_evaluated_key=None, local_vars_configuration=None):  # noqa: E501
        """AllAccountsResponseAccounts - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._items = None
        self._count = None
        self._scanned_count = None
        self._last_evaluated_key = None
        self.discriminator = None

        self.items = items
        self.count = count
        self.scanned_count = scanned_count
        self.last_evaluated_key = last_evaluated_key

    @property
    def items(self):
        """Gets the items of this AllAccountsResponseAccounts.  # noqa: E501


        :return: The items of this AllAccountsResponseAccounts.  # noqa: E501
        :rtype: AccountResponse
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this AllAccountsResponseAccounts.


        :param items: The items of this AllAccountsResponseAccounts.  # noqa: E501
        :type items: AccountResponse
        """
        if self.local_vars_configuration.client_side_validation and items is None:  # noqa: E501
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items

    @property
    def count(self):
        """Gets the count of this AllAccountsResponseAccounts.  # noqa: E501


        :return: The count of this AllAccountsResponseAccounts.  # noqa: E501
        :rtype: float
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this AllAccountsResponseAccounts.


        :param count: The count of this AllAccountsResponseAccounts.  # noqa: E501
        :type count: float
        """
        if self.local_vars_configuration.client_side_validation and count is None:  # noqa: E501
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    @property
    def scanned_count(self):
        """Gets the scanned_count of this AllAccountsResponseAccounts.  # noqa: E501


        :return: The scanned_count of this AllAccountsResponseAccounts.  # noqa: E501
        :rtype: float
        """
        return self._scanned_count

    @scanned_count.setter
    def scanned_count(self, scanned_count):
        """Sets the scanned_count of this AllAccountsResponseAccounts.


        :param scanned_count: The scanned_count of this AllAccountsResponseAccounts.  # noqa: E501
        :type scanned_count: float
        """
        if self.local_vars_configuration.client_side_validation and scanned_count is None:  # noqa: E501
            raise ValueError("Invalid value for `scanned_count`, must not be `None`")  # noqa: E501

        self._scanned_count = scanned_count

    @property
    def last_evaluated_key(self):
        """Gets the last_evaluated_key of this AllAccountsResponseAccounts.  # noqa: E501


        :return: The last_evaluated_key of this AllAccountsResponseAccounts.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._last_evaluated_key

    @last_evaluated_key.setter
    def last_evaluated_key(self, last_evaluated_key):
        """Sets the last_evaluated_key of this AllAccountsResponseAccounts.


        :param last_evaluated_key: The last_evaluated_key of this AllAccountsResponseAccounts.  # noqa: E501
        :type last_evaluated_key: dict(str, str)
        """
        if self.local_vars_configuration.client_side_validation and last_evaluated_key is None:  # noqa: E501
            raise ValueError("Invalid value for `last_evaluated_key`, must not be `None`")  # noqa: E501

        self._last_evaluated_key = last_evaluated_key

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllAccountsResponseAccounts):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AllAccountsResponseAccounts):
            return True

        return self.to_dict() != other.to_dict()
