# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.all_transactions_response import AllTransactionsResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestAllTransactionsResponse(unittest.TestCase):
    """AllTransactionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AllTransactionsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.all_transactions_response.AllTransactionsResponse()  # noqa: E501
        if include_optional :
            return AllTransactionsResponse(
                transactions = [
                    openapi_client.models.transaction_response.TransactionResponse(
                        transaction_id = '', 
                        account_id = '', 
                        business_id = '', 
                        amount = 1.337, 
                        note = '', 
                        payment_provider = 'stripe', 
                        payment_id = '', 
                        created_at = 1.337, 
                        modified_at = 1.337, )
                    ]
            )
        else :
            return AllTransactionsResponse(
                transactions = [
                    openapi_client.models.transaction_response.TransactionResponse(
                        transaction_id = '', 
                        account_id = '', 
                        business_id = '', 
                        amount = 1.337, 
                        note = '', 
                        payment_provider = 'stripe', 
                        payment_id = '', 
                        created_at = 1.337, 
                        modified_at = 1.337, )
                    ],
        )

    def testAllTransactionsResponse(self):
        """Test AllTransactionsResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
