# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.post_account_request import PostAccountRequest  # noqa: E501
from openapi_client.rest import ApiException

class TestPostAccountRequest(unittest.TestCase):
    """PostAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostAccountRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.post_account_request.PostAccountRequest()  # noqa: E501
        if include_optional :
            return PostAccountRequest(
                account_id = '', 
                name = ''
            )
        else :
            return PostAccountRequest(
                account_id = '',
        )

    def testPostAccountRequest(self):
        """Test PostAccountRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
