/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AccountUsageBillingAdjustmentsResponse struct for AccountUsageBillingAdjustmentsResponse
type AccountUsageBillingAdjustmentsResponse struct {
	Adjustments []AccountUsageBillingAdjustmentsResponseAdjustmentsInner `json:"adjustments"`
}

// NewAccountUsageBillingAdjustmentsResponse instantiates a new AccountUsageBillingAdjustmentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountUsageBillingAdjustmentsResponse(adjustments []AccountUsageBillingAdjustmentsResponseAdjustmentsInner) *AccountUsageBillingAdjustmentsResponse {
	this := AccountUsageBillingAdjustmentsResponse{}
	this.Adjustments = adjustments
	return &this
}

// NewAccountUsageBillingAdjustmentsResponseWithDefaults instantiates a new AccountUsageBillingAdjustmentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountUsageBillingAdjustmentsResponseWithDefaults() *AccountUsageBillingAdjustmentsResponse {
	this := AccountUsageBillingAdjustmentsResponse{}
	return &this
}

// GetAdjustments returns the Adjustments field value
func (o *AccountUsageBillingAdjustmentsResponse) GetAdjustments() []AccountUsageBillingAdjustmentsResponseAdjustmentsInner {
	if o == nil {
		var ret []AccountUsageBillingAdjustmentsResponseAdjustmentsInner
		return ret
	}

	return o.Adjustments
}

// GetAdjustmentsOk returns a tuple with the Adjustments field value
// and a boolean to check if the value has been set.
func (o *AccountUsageBillingAdjustmentsResponse) GetAdjustmentsOk() ([]AccountUsageBillingAdjustmentsResponseAdjustmentsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Adjustments, true
}

// SetAdjustments sets field value
func (o *AccountUsageBillingAdjustmentsResponse) SetAdjustments(v []AccountUsageBillingAdjustmentsResponseAdjustmentsInner) {
	o.Adjustments = v
}

func (o AccountUsageBillingAdjustmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["adjustments"] = o.Adjustments
	}
	return json.Marshal(toSerialize)
}

type NullableAccountUsageBillingAdjustmentsResponse struct {
	value *AccountUsageBillingAdjustmentsResponse
	isSet bool
}

func (v NullableAccountUsageBillingAdjustmentsResponse) Get() *AccountUsageBillingAdjustmentsResponse {
	return v.value
}

func (v *NullableAccountUsageBillingAdjustmentsResponse) Set(val *AccountUsageBillingAdjustmentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountUsageBillingAdjustmentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountUsageBillingAdjustmentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountUsageBillingAdjustmentsResponse(val *AccountUsageBillingAdjustmentsResponse) *NullableAccountUsageBillingAdjustmentsResponse {
	return &NullableAccountUsageBillingAdjustmentsResponse{value: val, isSet: true}
}

func (v NullableAccountUsageBillingAdjustmentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountUsageBillingAdjustmentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


