# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule .Model.AllAccountsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounts
  ]

  @type t :: %__MODULE__{
    :accounts => [.Model.AccountResponse.t]
  }
end

defimpl Poison.Decoder, for: .Model.AllAccountsResponse do
  import .Deserializer
  def decode(value, options) do
    value
    |> deserialize(:accounts, :list, .Model.AccountResponse, options)
  end
end

