# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule .Model.AllAccountsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accounts,
    :total
  ]

  @type t :: %__MODULE__{
    :accounts => .Model.AllAccountsResponseAccounts.t,
    :total => float()
  }
end

defimpl Poison.Decoder, for: .Model.AllAccountsResponse do
  import .Deserializer
  def decode(value, options) do
    value
    |> deserialize(:accounts, :struct, .Model.AllAccountsResponseAccounts, options)
  end
end

