# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule .Model.AllTransactionsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :transactions,
    :total
  ]

  @type t :: %__MODULE__{
    :transactions => .Model.AllTransactionsResponseTransactions.t,
    :total => float()
  }
end

defimpl Poison.Decoder, for: .Model.AllTransactionsResponse do
  import .Deserializer
  def decode(value, options) do
    value
    |> deserialize(:transactions, :struct, .Model.AllTransactionsResponseTransactions, options)
  end
end

