# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule .Model.PatchAccountRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :accountName
  ]

  @type t :: %__MODULE__{
    :accountName => String.t | nil
  }
end

defimpl Poison.Decoder, for: .Model.PatchAccountRequest do
  def decode(value, _options) do
    value
  end
end

