# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule .Model.TransactionStatsResponseDailyInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :date,
    :incomingAmount,
    :outgoingAmount,
    :incomingCount,
    :outgoingCount
  ]

  @type t :: %__MODULE__{
    :date => String.t,
    :incomingAmount => float(),
    :outgoingAmount => float(),
    :incomingCount => float(),
    :outgoingCount => float()
  }
end

defimpl Poison.Decoder, for: .Model.TransactionStatsResponseDailyInner do
  def decode(value, _options) do
    value
  end
end

